### PR TITLE
Compatibility with Rails 5.0

### PR DESCRIPTION
**Pull request by pschambacher**
:octopus::computer: 

/cc @grosser 

### Steps to merge
 - [ ] #12 merged

### CODE REVIEW

**Comment by grosser** [comment]
:+1: ... travis is not happy though ...

**Comment by pschambacher** [comment]
Forgot the bloody exclude for Ruby 2.0 and 2.1

**Comment by pschambacher** [comment]
@grosser good to go
Should we move the repo to `/zendesk` after this?

**Comment by grosser** [comment]
@eac want to move it over to zendesk ? (I think you have to move it to me first and I can move it into the org then)

**Comment by grosser** [comment]
0.4.0

**Comment by eac** [comment]
@grosser Sure thing. looks like you need to delete your fork first:

`Error: grosser/predictive_load already exists`

**Comment by grosser** [comment]
done!

**Comment by grosser** [comment]
@eac can you try again ?

**Comment by grosser** [comment]
Yeah that worked, thx!
Welcome to zendesk/predictive_load :D

**Comment by pschambacher** [comment]
:tada:

**Pull request merged**
